# Judge0 Core
# RAILS_ENV=production
JUDGE0_TELEMETRY_ENABLE=false

# PostgreSQL
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0
DATABASE_URL=postgres://judge0:judge0@db:5432/judge0

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0
REDIS_URL=redis://:judge0@redis:6379/0

# AWS VM runtime defaults
MEMORY_LIMIT=5120000
MAX_MEMORY_LIMIT=5120000
MAX_PROCESS_AND_OR_THREAD_COUNT=120
CPU_TIME_LIMIT=5
WALL_TIME_LIMIT=10

# Disable cgroups to support WSL2 / Docker Desktop
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
