import React, { useContext } from "react";
import { Link } from "react-router-dom";
import { AuthContext } from "../context/authStore";
import { Sun, Moon, ArrowLeft, FileText, Coffee } from "lucide-react";

export default function TermsPage() {
  const { theme, toggleTheme } = useContext(AuthContext);

  return (
    <div className="min-h-screen bg-background text-main flex flex-col font-sans transition-colors duration-300 relative overflow-hidden">
      {/* Background dot grid pattern */}
      <div className="absolute inset-0 bg-grid mask-radial pointer-events-none -z-10"></div>



      {/* Main Content */}
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16">
        {/* Back Link */}
        <Link to="/" className="inline-flex items-center gap-2 text-xs font-semibold text-gray-500 hover:text-white transition-colors mb-8 group cursor-pointer">
          <ArrowLeft size={14} className="group-hover:-translate-x-0.5 transition-transform" />
          Back to Home
        </Link>

        {/* Title */}
        <div className="space-y-4 mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 text-[10px] font-bold uppercase tracking-wider">
            <FileText size={12} /> Legal
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">Terms and Conditions</h1>
          <p className="text-xs text-gray-500 font-mono">Last updated: July 20, 2026</p>
        </div>

        {/* Legal Text */}
        <div className="space-y-10 text-sm text-gray-400 leading-relaxed">
          <p>
            Please read these terms and conditions carefully before using our service. By accessing or using the QuizPortal platform, you agree to be bound by these Terms and accept all legal consequences. If you do not agree to these terms and conditions, in whole or in part, please do not use the service.
          </p>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Use of Platform</h2>
            <p>
              QuizPortal provides tools for student coding evaluations and assessments. You agree to use these tools solely for institutional, personal, non-commercial educational purposes. You may not reverse-engineer, scrape, or systematically extract data from our platform or active compiler sockets.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate our terms or attempt sandbox exploitation.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Content Generation</h2>
            <p>
              Our compilers and AI modules generate interview/exam questions, test cases, and grade assessments. While we strive for correctness, automated feedback and compilation grades are provided 'as is' without warranties. You should not rely solely on automated feedback for critical career or academic decisions.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Intellectual Property</h2>
            <p>
              All platform design, code, styles, compilers, and original content are owned by QuizPortal. User-uploaded code submissions, answers, and profile information remain your intellectual property, but you grant your college and QuizPortal a license to process and compile them for the purpose of providing the evaluation service.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Content Sources & Accuracy</h2>
            <p>
              Content displayed on the QuizPortal platform is either generated by Artificial Intelligence, authored by instructors, or curated from public educational resources. We do not guarantee the absolute accuracy, completeness, or reliability of any third-party questions or solutions.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Third-Party Resources & Educational Use</h2>
            <p>
              Notes, reference links, and embedded media are provided strictly for educational purposes. We are not sponsored by, endorsed by, or affiliated with the original content creators. All third-party copyrights belong to their respective owners.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-bold text-white tracking-tight">Limitation of Liability</h2>
            <p>
              In no event shall QuizPortal, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800/10 py-12 px-6">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="text-center md:text-left">
            <span className="text-lg font-bold bg-clip-text text-transparent bg-linear-to-r from-blue-600 to-purple-600">QuizPortal</span>
            <p className="text-[11px] text-gray-600 mt-1">Coding assessments for engineering colleges.</p>
            <p className="text-[10px] text-gray-500 mt-2 font-medium flex items-center justify-center md:justify-start gap-1">
              Made with <Coffee size={12} className="text-gray-500 inline-block" />, patience, and far too many test cases.
            </p>
          </div>
          <div className="flex gap-6 text-[11px] text-gray-600">
            <Link to="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link to="/terms" className="hover:text-white transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
